plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
}

application {
    mainClass = 'com.codealpha.App'
}

tasks.named('test') {
    useJUnitPlatform()
}

// Package executable Fat JAR with all dependencies included
jar {
    manifest {
        attributes(
            'Main-Class': 'com.codealpha.App'
        )
    }
    from {
        configurations.runtimeClasspath.getFiles().collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
