pipeline {
    agent any

    environment {
        IMAGE_NAME = 'task3-java-app'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('Task3_Gradle_Java_App') {
                    echo 'Building Java App with Gradle Wrapper...'
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Task3_Gradle_Java_App') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Deploy / Run Container') {
            steps {
                echo 'Testing Application Execution inside Container...'
                sh 'docker run --rm $IMAGE_NAME'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete.'
        }
        success {
            echo 'Task 3 CI/CD Pipeline Succeeded!'
        }
    }
}
