pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('Task3_Gradle_Java_App') {
                    echo 'Building Java App with Gradle Wrapper...'
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Verify Executable JAR') {
            steps {
                dir('Task3_Gradle_Java_App') {
                    echo 'Executing compiled Fat JAR...'
                    sh 'java -jar build/libs/codealpha-java-gradle-app.jar'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete.'
        }
        success {
            echo 'Task 3 CI/CD Pipeline Succeeded!'
        }
    }
}
